VALID_TRANSITIONS = {
    "ASSIGNED": ["ACKNOWLEDGED"],
    "ACKNOWLEDGED": ["IN_PROGRESS"],
    "IN_PROGRESS": ["RESOLVED"],
    "SLA_BREACHED": ["ESCALATED"],
    "ESCALATED": ["IN_PROGRESS", "RESOLVED"]
}
